name: Manual Build and Release

on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: "Which version increment?"
                required: true
                default: "patch"
                type: choice
                options:
                    - major
                    - minor
                    - patch
            isBeta:
                description: "Build as a beta release?"
                required: true
                default: "false"
                type: choice
                options:
                    - "false"
                    - "true"

permissions:
    contents: write
    issues: write
    pull-requests: write
    security-events: write

jobs:
    version-update-and-build:
        runs-on: windows-latest
        strategy:
            matrix:
                runtime: [win-x64, win-x86, win-arm64]
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  app-id: ${{ vars.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: recursive
                  token: ${{ steps.app-token.outputs.token }}

            - name: Set Git User
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Cache NuGet packages
              uses: actions/cache@v4
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Setup GitVersion
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y python3
                  sudo apt-get install -y xmlstarlet
                  chmod +x .github/scripts/increment_version.py

            # Environment-specific configurations
            # - name: Set Build Environment
            #   run: |
            #     if [ "${{ github.event.inputs.isBeta }}" == "true" ]; then
            #       echo "BUILD_CONFIG=Beta" >> $GITHUB_ENV
            #     else
            #       echo "BUILD_CONFIG=Release" >> $GITHUB_ENV
            #     fi

            - name: Determine Version with GitVersion
              id: gitversion
              run: |
                  RELEASE_TYPE="${{ github.event.inputs.releaseType }}" \
                    .github/scripts/increment_version.py
              env:
                  RELEASE_TYPE: ${{ github.event.inputs.releaseType }}

            - name: Debug GitVersion Output
              run: |
                  echo "FullSemVer: ${{ steps.gitversion.outputs.fullsemver }}"
                  echo "Major: ${{ steps.gitversion.outputs.major }}"
                  echo "Minor: ${{ steps.gitversion.outputs.minor }}"
                  echo "Patch: ${{ steps.gitversion.outputs.patch }}"

            - name: Update Directory.Build.props Versions
              run: |
                  MAJOR="${{ steps.gitversion.outputs.major }}"
                  MINOR="${{ steps.gitversion.outputs.minor }}"
                  PATCH="${{ steps.gitversion.outputs.patch }}"
                  
                  sed -i "s|<MajorVersion>.*</MajorVersion>|<MajorVersion>${MAJOR}</MajorVersion>|" Directory.Build.props
                  sed -i "s|<MinorVersion>.*</MinorVersion>|<MinorVersion>${MINOR}</MinorVersion>|" Directory.Build.props
                  sed -i "s|<PatchVersion>.*</PatchVersion>|<PatchVersion>${PATCH}</PatchVersion>|" Directory.Build.props

            - name: Handle Beta Builds
              run: |
                  sed -i "s|<IsBeta>.*</IsBeta>|<IsBeta>${{ github.event.inputs.isBeta }}</IsBeta>|" Directory.Build.props

            - name: Commit Updated Directory.Build.props
              run: |
                  git add Directory.Build.props
                  git commit -m "chore: update version to ${{ steps.gitversion.outputs.fullsemver }} (isBeta=${{ github.event.inputs.isBeta }})"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set Up .NET (v9)
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.x

            - name: Restore Dependencies
              run: dotnet restore

            - name: Build Solution
              run: dotnet build --configuration Release --parallel

            - name: Run Tests
              run: dotnet test --configuration Release --no-build --verbosity normal
              continue-on-error: true

            # Security scanning
            # - name: Run Security Scan
            #   uses: securecodewarrior/github-action-add-sarif@v1
            #   with:
            #     sarif-file: 'security-scan-results.sarif'
            #   continue-on-error: true

            - name: Publish Solution Components
              run: |
                  # Create main publish directory
                  mkdir -p ./publish/ModForwarder-${{ matrix.runtime }}
                  
                  # Publish Console Tooling with optimizations
                  dotnet publish PenumbraModForwarder.ConsoleTooling \
                    -c Release \
                    -p:PublishSingleFile=true \
                    -p:PublishReadyToRun=true \
                    --self-contained=true \
                    -p:DebugType=None -p:DebugSymbols=false \
                    -r ${{ matrix.runtime }} \
                    -o ./publish/temp-console-${{ matrix.runtime }} \
                    -f net9.0
                  
                  # Publish UI Application with optimizations
                  dotnet publish PenumbraModForwarder.UI \
                    -c Release \
                    -p:PublishSingleFile=true \
                    -p:PublishReadyToRun=true \
                    --self-contained=true \
                    -p:DebugType=None -p:DebugSymbols=false \
                    -r ${{ matrix.runtime }} \
                    -o ./publish/temp-ui-${{ matrix.runtime }} \
                    -f net9.0
                  
                  # Publish Background Worker with optimizations
                  dotnet publish PenumbraModForwarder.BackgroundWorker \
                    -c Release \
                    -p:PublishSingleFile=true \
                    -p:PublishReadyToRun=true \
                    --self-contained=true \
                    -p:DebugType=None -p:DebugSymbols=false \
                    -r ${{ matrix.runtime }} \
                    -o ./publish/temp-worker-${{ matrix.runtime }} \
                    -f net9.0
                  
                  # Move all files to the root ModForwarder directory
                  cp -r ./publish/temp-console-${{ matrix.runtime }}/* ./publish/ModForwarder-${{ matrix.runtime }}/
                  cp -r ./publish/temp-ui-${{ matrix.runtime }}/* ./publish/ModForwarder-${{ matrix.runtime }}/
                  cp -r ./publish/temp-worker-${{ matrix.runtime }}/* ./publish/ModForwarder-${{ matrix.runtime }}/
                  
                  # Clean up temporary directories
                  rm -rf ./publish/temp-console-${{ matrix.runtime }} ./publish/temp-ui-${{ matrix.runtime }} ./publish/temp-worker-${{ matrix.runtime }}

            - name: Validate Executables
              run: |
                  # Verify executables were created and are not zero-byte
                  for exe in ./publish/ModForwarder-${{ matrix.runtime }}/*.exe; do
                    if [ ! -s "$exe" ]; then
                      echo "Error: $exe is empty or missing"
                      exit 1
                    fi
                    echo "✓ $(basename "$exe") - $(du -h "$exe" | cut -f1)"
                  done

            - name: Run GitVersion again
              id: gitversion2
              shell: bash
              run: |
                  CURRENT_MAJOR=$(xmlstarlet sel -t -v "//Project/PropertyGroup/MajorVersion" Directory.Build.props)
                  CURRENT_MINOR=$(xmlstarlet sel -t -v "//Project/PropertyGroup/MinorVersion" Directory.Build.props)
                  CURRENT_PATCH=$(xmlstarlet sel -t -v "//Project/PropertyGroup/PatchVersion" Directory.Build.props)
                  
                  FULL_SEMVER="${CURRENT_MAJOR}.${CURRENT_MINOR}.${CURRENT_PATCH}"
                  PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
                  
                  echo "FULL_SEMVER=$FULL_SEMVER" >> $GITHUB_ENV
                  echo "MAJORMINORPATCH=$FULL_SEMVER" >> $GITHUB_ENV
                  echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

            - name: Get Latest Release from GitHub
              id: get-release
              uses: actions/github-script@v7
              with:
                  script: |
                      const { data: releases } = await github.rest.repos.listReleases({
                        owner: context.repo.owner,
                        repo: context.repo.repo
                      });
                      if (!releases || releases.length === 0) {
                        core.setOutput("latest_tag", "");
                      } else {
                        core.setOutput("latest_tag", releases[0].tag_name);
                      }

            - name: Compare GitHub Tag with GitVersion (SemVer)
              shell: bash
              run: |
                  GH_LATEST_TAG_RAW="${{ steps.get-release.outputs.latest_tag }}"
                  FULL_SEMVER="${{ env.FULL_SEMVER }}"
                  
                  if [ -z "$GH_LATEST_TAG_RAW" ]; then
                    echo "No previous GitHub release found. We'll do a brand-new release."
                    exit 0
                  fi
                  
                  GH_LATEST_TAG="${GH_LATEST_TAG_RAW#v}"
                  CLEAN_SEMVER="${FULL_SEMVER%%-*}"
                  
                  GH_MAJOR="$(echo "$GH_LATEST_TAG" | cut -d'.' -f1)"
                  GH_MINOR="$(echo "$GH_LATEST_TAG" | cut -d'.' -f2)"
                  GH_PATCH="$(echo "$GH_LATEST_TAG" | cut -d'.' -f3)"
                  GIT_MAJOR="$(echo "$CLEAN_SEMVER" | cut -d'.' -f1)"
                  GIT_MINOR="$(echo "$CLEAN_SEMVER" | cut -d'.' -f2)"
                  GIT_PATCH="$(echo "$CLEAN_SEMVER" | cut -d'.' -f3)"
                  
                  echo "GitHub's release version: $GH_MAJOR.$GH_MINOR.$GH_PATCH"
                  echo "Local version:           $GIT_MAJOR.$GIT_MINOR.$GIT_PATCH"
                  
                  if [ "$GIT_MAJOR" -gt "$GH_MAJOR" ] || \
                     { [ "$GIT_MAJOR" -eq "$GH_MAJOR" ] && [ "$GIT_MINOR" -gt "$GH_MINOR" ]; } || \
                     { [ "$GIT_MAJOR" -eq "$GH_MAJOR" ] && [ "$GIT_MINOR" -eq "$GH_MINOR" ] && [ "$GIT_PATCH" -gt "$GH_PATCH" ]; }; then
                    echo "Newer version found locally; proceed with release."
                  else
                    echo "Local version is NOT newer. You might decide to skip or handle differently."
                  fi

            - name: Generate Release Notes
              id: gen-notes
              shell: bash
              run: |
                  GITVERSION_PREVIOUS_TAG="${{ env.PREVIOUS_TAG }}"
                  GH_LATEST_TAG_RAW="${{ steps.get-release.outputs.latest_tag }}"
                  FALLBACK_TAG="$GH_LATEST_TAG_RAW"
                  
                  if [ -z "$GITVERSION_PREVIOUS_TAG" ] && [ -n "$GH_LATEST_TAG_RAW" ]; then
                    echo "No local previous tag found; falling back to GitHub release tag '$FALLBACK_TAG'."
                    GITVERSION_PREVIOUS_TAG="$FALLBACK_TAG"
                  fi
                  
                  if [ -z "$GITVERSION_PREVIOUS_TAG" ]; then
                    echo "COMMITS<<EOF" >> "$GITHUB_ENV"
                    echo "No previous tag — skipping commit history." >> "$GITHUB_ENV"
                    echo "EOF" >> "$GITHUB_ENV"
                  else
                    COMMITS=$(git log "$GITVERSION_PREVIOUS_TAG..HEAD" --pretty=format:'- %s (%h)' | grep -v "chore: update version to")
                  
                    echo "COMMITS<<EOF" >> "$GITHUB_ENV"
                    echo "$COMMITS" >> "$GITHUB_ENV"
                    echo "EOF" >> "$GITHUB_ENV"
                  fi

            - name: Create Release ZIP
              run: |
                  cd ./publish
                  zip -r ModForwarder-${{ matrix.runtime }}.v${{ env.MAJORMINORPATCH }}.zip ModForwarder-${{ matrix.runtime }}/
                  cd ..

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ModForwarder-${{ matrix.runtime }}-v${{ env.MAJORMINORPATCH }}
                  path: ./publish/ModForwarder-${{ matrix.runtime }}.v${{ env.MAJORMINORPATCH }}.zip
                  retention-days: 90

            - name: Create GitHub Release (only for win-x64)
              if: matrix.runtime == 'win-x64'
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ env.MAJORMINORPATCH }}
                  name: Release v${{ env.MAJORMINORPATCH }}
                  body: |
                      ## Changes (since last release):
                      ${{ env.COMMITS }}
                      
                      ## Available Downloads:
                      - `ModForwarder-win-x64.v${{ env.MAJORMINORPATCH }}.zip` - Windows 64-bit
                      - `ModForwarder-win-x86.v${{ env.MAJORMINORPATCH }}.zip` - Windows 32-bit  
                      - `ModForwarder-win-arm64.v${{ env.MAJORMINORPATCH }}.zip` - Windows ARM64
                  files: |
                      ./publish/ModForwarder-win-x64.v${{ env.MAJORMINORPATCH }}.zip
                      ./publish/ModForwarder-win-x86.v${{ env.MAJORMINORPATCH }}.zip
                      ./publish/ModForwarder-win-arm64.v${{ env.MAJORMINORPATCH }}.zip
                  draft: false
                  prerelease: ${{ github.event.inputs.isBeta == 'true' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Notify on Success
              if: success()
              run: |
                  echo "✅ Release v${{ env.MAJORMINORPATCH }} created successfully for ${{ matrix.runtime }}!"
                  if [ "${{ matrix.runtime }}" == "win-x64" ]; then
                    echo "📦 Download: https://github.com/${{ github.repository }}/releases/tag/v${{ env.MAJORMINORPATCH }}"
                  fi

            - name: Rollback on Failure
              if: failure()
              run: |
                  echo "❌ Build failed for ${{ matrix.runtime }}, rolling back version commit..."
                  git reset --hard HEAD~1
                  git push --force-with-lease
              continue-on-error: true